---
title: "Xabier data"
output: html_document
date: "2024-04-09"
---

```{r}
library(tidyverse)
library(Seurat)
library(readr)
```

```{r}
# load data 
expression<-readRDS("~/Downloads/merged_scRNA_unfiltered_IDs_faye.RDS")
```


```{r}
#para la expresion, cargo el data. aunq tambien esta el scaled.data. no se 100% bien cual de los dos deberia cargar. no se por que han escalado los datos

expression_matrix<-expression@assays$RNA@data
metadata<-expression@meta.data
metadata$celltype<-Idents(expression)
#mezclar las mitoticas con las no mitoticas.
metadata$celltype<-gsub("_M","",metadata$celltype)
metadata<-metadata %>% filter(!is.na(pseudotime))
table(metadata$celltype)/175
#hacer pseudobulks de 175 celulas. pq es lo mas justo para hacer 2 pseudobulks en pn3

#hacer los heatmaps con esto. y luego ponerle los picos, su trayectoria, motivos, y spacing. y
j<-1
for (cell in c("NSC","IPC","PN1","PN2","PN3")) {
  print(cell)
  metadata_cell<-metadata %>% filter(celltype==cell)
  metadata_cell<-metadata_cell %>% arrange(pseudotime)
  i<-1
  while ((i+175)<=length(metadata_cell$pseudotime)) {
    pseudobulk_cells<-rownames(metadata_cell)[i:(i+174)]
    pseudobulk_expression<-rowSums(as.matrix(expression_matrix[,pseudobulk_cells]))
    if (j==1) { pseudo_expression<-pseudobulk_expression}
    if (j>1) { pseudo_expression<-cbind(pseudo_expression,pseudobulk_expression)}
    i<-i+175
    j<-j+1
  }
}
colnames(pseudo_expression)
colnames(pseudo_expression)<-c(paste0("NSC_",1:11),paste0("IPC_",1:8),paste0("PN1_",1:9),paste0("PN2_",1:8),paste0("PN3_",1:2))

```

```{r}
# Cargamos la tabla de bHLHs (ya la he cargado previamente pero la
# pongo aquí por si acaso) 

table_bhlh<- read_csv('~/Downloads/Tesis/factors_classification.csv')
colnames(table_bhlh)[1] <- 'Symbol'
bhlh_symbol <- table_bhlh %>% pull(Symbol)

table_bhlh <- table_bhlh %>%
  select(Symbol,`Ledent2002+Simionato2007Name`) %>% 
  rename(Gene_family=`Ledent2002+Simionato2007Name`)
```


```{r 'heatmap imput'}
# creamos el dataset que incluya los datos de z-score para cada gen
z_score <- pseudo_expression %>% 
  as.data.frame() %>% 
  rownames_to_column('Symbol') %>%
  pivot_longer(-Symbol, names_to = 'Cell_type', values_to = 'expression') %>% 
  group_by(Symbol) %>% 
  mutate(Zscore=(expression - mean(expression))/sd(expression)) %>%
  ungroup() %>% 
  mutate(Group=gsub('\\_.*','',Cell_type),
         Pseudotime=gsub('.*\\_','',Cell_type),
         Pseudotime= factor(Pseudotime, levels = as.character(1:12)),
         Symbol=toupper(Symbol))

# Seleccionamos solo los bHLH y añadimos la información de la familia
heatmap_imput <- inner_join(table_bhlh, z_score, by='Symbol')

```


```{r 'zscore heatmap', fig.width=7, fig.height=16}
# cremaos un heatmap con los valores del zscore

heatmap <-  heatmap_imput %>%
  ungroup() %>% 
  ggplot(aes(x=Pseudotime, y=Symbol, fill= Zscore))+
  scale_fill_gradient2(  low = scales::muted("blue"), 
                         mid = "white", 
                         high = scales::muted("red")) +
  geom_tile()+
  #coord_equal()+
  facet_grid(Gene_family~Group, scales  = 'free', space = 'free', switch = 'y')+
  theme_bw()+
  theme(legend.position = 'bottom',
        strip.placement = "outside", 
        strip.background.x=element_rect(color = NA,
                                        fill=NA), 
        strip.background.y=element_rect(color = 'gray50',
                                        fill=NA),
        strip.text.y.left = element_text(angle = 0,
                                          hjust = 1,
                                          face = 'bold',
                                          color = 'gray30'),
        strip.text.x.top = element_text(face = 'bold', color = 'gray30'),
        axis.title.y=element_blank())

# ggsave(heatmap, filename = '~/heatmap.pdf',
#        device='pdf', height=16, width=7, units='in')
```


```{r 'raw heatmap', fig.width=7, fig.height=16}

# creamos un heatmpa con los valores raw 

heatmap_raw <-  heatmap_imput %>%
  ungroup() %>% 
  ggplot(aes(x=Pseudotime, y=Symbol, fill= expression))+
  scale_fill_gradient(low = "#caf0f8",high = '#03045e') +
  geom_tile()+
  #coord_equal()+
  facet_grid(Gene_family~Group, scales  = 'free', space = 'free', switch = 'y')+
  theme_bw()+
  theme(legend.position = 'bottom',
        strip.placement = "outside")+
  theme(strip.background.x=element_rect(color = NA,
                                        fill=NA), 
        strip.background.y=element_rect(color = 'gray50',
                                        fill=NA),
        strip.text.y.left = element_text(angle = 0,
                                          hjust = 1,
                                          face = 'bold',
                                          color = 'gray30'),
        strip.text.x.top = element_text(face = 'bold', color = 'gray30'),
        axis.title.y=element_blank())


# ggsave(heatmap_raw, filename = '~/heatmap_raw.pdf', 
#        device='pdf', height=16, width=7, units='in')
```

```{r}

# Comprobar la distribución del pseudotime entre distintos grupos
metadata %>% 
  ggplot(aes(x=reorder(celltype, pseudotime, FUN=median), y=pseudotime))+
    geom_violin(aes(fill=celltype),
                scale = "width",
                alpha=0.5,
                show.legend = FALSE,
                trim = TRUE)+
    geom_point(aes(color=celltype),
               size=0.4,
               alpha = 0.6, 
               position=position_jitter(height=0, width=.4),
               show.legend = FALSE)+
    theme_classic()+
    xlab('Type')+
    ylab('Pseudotime')+
    coord_flip()

# ggsave(filename='~/pseusotime_distribution.pdf',
#        device = "pdf",
#        height = 6, width =6 , units = "in")


```

```{r}
# creamos el dataframe necesario para estudiar la distribución
bHLH_expression <- expression_matrix %>% 
  as.matrix() %>%
  t() %>% 
  as.data.frame() %>% 
  setNames(colnames(.) %>% toupper()) %>% 
  select(any_of(bhlh_symbol)) %>% 
  rownames_to_column('Cell_ID')


bHLHs_expressed_by_cell<- bHLH_expression %>%
  pivot_longer(-Cell_ID, names_to = 'Gene', values_to = 'Expression') %>% 
  filter(Expression!=0) %>% 
  group_by(Cell_ID) %>% 
  summarise(Expressed_bHLH=paste(Gene, collapse = ','))
  
grouped_pseudotime <- metadata %>% 
  rownames_to_column('Cell_ID') %>% 
  select(Cell_ID,celltype, pseudotime) %>% 
  group_by(celltype) %>% 
  arrange(pseudotime) %>% 
  mutate(Pseudotime_group=rep(1:ceiling(n()/175),each=175, length.out=n())) %>% 
  group_by(celltype, Pseudotime_group) %>% 
  filter(n()==175) 

bHLHs_expressed_by_cell_meta <- inner_join(grouped_pseudotime, bHLHs_expressed_by_cell) 
```


```{r, fig.width=6, fig.height= 9}
plot_imput <- bHLHs_expressed_by_cell_meta %>% 
  ungroup() %>% 
  mutate(NEUROG= grepl('.*NEUROG.*',Expressed_bHLH),
         NEUROD= grepl('.*NEUROD.*',Expressed_bHLH),
         TCF= grepl('.*TCF.*',Expressed_bHLH),
         SOX= grepl('.*SOX.*',Expressed_bHLH),
         ID= grepl('.*ID.*',Expressed_bHLH)
  ) %>% 
  pivot_longer(-c(Cell_ID,celltype, pseudotime, Pseudotime_group, Expressed_bHLH),
               names_to = 'family',
               values_to = 'expression') %>% 
  filter(expression==TRUE) %>% 
  group_by(Cell_ID,celltype, pseudotime, Pseudotime_group, Expressed_bHLH) %>% 
  summarise(families=paste(family, collapse = ','),
            families_list= list(family)) %>% 
  ungroup()

library(ggupset)

plot_imput %>% 
  group_by(celltype, Pseudotime_group) %>% 
  count(families) %>% 
  mutate(percent=n/sum(n)) %>% 
  ungroup() %>% 
  mutate(families_list=strsplit(families, ','),
         Pseudotime_group=factor(Pseudotime_group, levels=as.character(12:1)),
         celltype=factor(celltype, levels=c('NSC','IPC','PN1','PN2','PN3'))) %>% 
  ggplot(aes(x=families_list, y=Pseudotime_group)) +
    facet_grid(celltype~., space = 'free', scales = 'free_y')+
    geom_point(aes(size=percent, color=percent))+
    scale_x_mergelist(sep = ",", position='top') +
    axis_combmatrix(sep = ",")+
  theme_classic()+
  theme(axis.title.y= element_text(angle=270),
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5),"inches"))+
  scale_color_gradient(low = "#caf0f8",high = '#03045e', guide = 'legend') 


```

```{r, fig.width=6, fig.height=1.8}


a <- grouped_pseudotime %>% 
  inner_join(metadata %>% rownames_to_column('Cell_ID')) %>% 
  group_by(celltype, Pseudotime_group) %>% 
   summarise(G2M= sum(Phase == 'G2M', na.rm = TRUE),
             Features= sum(nFeature_RNA, na.rm = TRUE)) %>% 
  mutate(celltype=factor(celltype, levels=c('NSC','IPC','PN1','PN2','PN3')),
         Pseudotime_group=factor(Pseudotime_group, levels=as.character(1:12))) %>% 
  arrange(celltype,Pseudotime_group)


a %>% 
  pivot_longer(-c(celltype, Pseudotime_group), 
               names_to = 'metadata', 
               values_to = 'Value') %>% 
  group_by(metadata) %>% 
  mutate(Normalized= (Value - min(Value)) / (max(Value) - min(Value))) %>%
  ggplot(aes(x=Pseudotime_group, y=metadata, fill= Normalized))+
  scale_fill_gradient(low = "gray90",high = 'gray30') +
  geom_tile()+
  facet_grid(~celltype, scales  = 'free', space = 'free')+
  theme_bw()+
  theme(legend.position = 'bottom',
        strip.placement = "outside", 
        strip.background.x=element_rect(color = NA,
                                        fill=NA), 
        strip.text.x.top = element_text(face = 'bold', color = 'gray30'),
        axis.title.y=element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x=element_blank())
```


```{r}
d <- data.frame(x=c("A","B","C"),y=c(1,2,3))

ggplot(d,aes(x,y)) +
  geom_blank() +
  geom_rect(aes(xmin=as.numeric(x)-.5,
                xmax=as.numeric(x)+.5,
                ymin=-Inf,
                ymax=Inf,
                fill=x))+ 
  geom_bar(stat="identity") 


case
```

# retomar el tema patterning centers 

```{r}
Manno_mouse <- readRDS('/projects_ng/SC_DATA/Manno2021/mdev_seu_0503_2021.rds')
Manno_mouse <- UpdateSeuratObject(Manno_mouse)
```

```{r}
library(Matrix)
Manno_RNA <- Manno_mouse[["RNA"]]$data %>% 
  Matrix(as.matrix(.),sparse = T)

rownames(Manno_RNA) <- toupper(rownames(Manno_RNA))

```


```{r}
# Filtramos solo los valores de los genes bHLH

table_bhlh<- read_csv('/users/genomics/josema/Trevino/factors_classification.csv')
colnames(table_bhlh)[1] <- 'Symbol'
bhlh_symbol <- table_bhlh %>% pull(Symbol)

table_bhlh <- table_bhlh %>%
  select(Symbol,`Ledent2002+Simionato2007Name`) %>% 
  rename(Gene_family=`Ledent2002+Simionato2007Name`)

bhlh_index <- which(rownames(Manno_RNA)%in%table_bhlh$Symbol)

Manno_RNA_bhlh <- Manno_RNA[bhlh_index,]
```

```{r}
Manno_combinations_with_metadata <- Manno_RNA_bhlh %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column('Cell') %>% 
  pivot_longer(-Cell, names_to = 'Gene', values_to = 'Expression') %>% 
  filter(Expression>0) %>% 
  filter(grepl('NEUROG|NEUROD|TCF|ID',Gene)) %>% 
  group_by(Cell) %>% 
  arrange(Gene) %>% 
  summarise(Id= paste( Gene, collapse = ',')) %>% 
  rowwise() %>% 
  mutate(class=stri_extract_all(Id, regex='NEUROG|NEUROD|TCF|ID'),
         class_ID_TCF_extended=stri_extract_all(Id,
                                regex='TCF[[:digit:]]*|ID[[:digit:]]*'),
         class=toString(unique(unlist(class))),
         class_ID_TCF_extended=toString(unique(unlist(class_ID_TCF_extended)))) %>% 
  inner_join(Manno_mouse@meta.data %>% 
               as.data.frame() %>%  
               rownames_to_column('Cell') %>% 
               select(Cell, Age, Subclass))
```

```{r}


Patterning_centers <- c('Cortical hem',
                        
                        'Zona limitans intrathalamica',
                        
                        'Anteromedial cerebral pole',
                        
                        'Floor plate',
                        'Midbrain floor plate',
                        'Hindbrain floor plate',

                        
                        'Roof plate',
                        'Hindbrain roof plate',
                        'Diencephalic roof plate')

age_order=c('e7.0', 'e8.0', 'e8.5', 'e9.0', 'e10.0',
  'e11.0', 'e12.0', 'e12.5', 'e13.0','e13.5',
  'e14.0', 'e14.5', 'e15.0','e15.5', 'e16.0',
  'e16.25','e16.5', 'e17.0', 'e17.5','e18.0')

Manno_combinations_with_metadata_upset_imput <- 
  Manno_combinations_with_metadata %>% 
  mutate( Age=  factor(Age, levels= rev(age_order))) %>%  
  filter(Subclass %in% Patterning_centers) %>% 
  mutate(Subclass = factor(Subclass, levels= Patterning_centers))


library(ggupset)

plot <- Manno_combinations_with_metadata_upset_imput %>% 
  group_by(Subclass,Age) %>% 
  count(class) %>% 
  mutate(percent=n/sum(n)) %>% 
  ungroup() %>% 
  mutate(families_list=strsplit(class, ',')) %>% 
  ggplot(aes(x=families_list, y=Age)) +
    geom_point(aes(size=percent, color=percent))+
    scale_x_upset(position="top")+
    facet_grid(Subclass~., scales = 'free_y', space = 'free_y')+
  theme_classic()+
  theme(axis.title.y= element_text(angle=270),
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5),"inches"))+
  scale_color_gradient(low = "#caf0f8",high = '#03045e', guide = 'legend') 

ggsave(plot,
       filename='manno_coexpression_plot.pdf',
       device = "pdf",
       height = 16, width =8, units = "in")  
```

Voy a hacer zoom en las ID protein y las TCF

```{r}

plot <- Manno_combinations_with_metadata_upset_imput %>% 
  group_by(Age) %>% 
  count(class_ID_TCF_extended) %>% 
  mutate(percent=n/sum(n)) %>% 
  ungroup() %>% 
  mutate(families_list=strsplit(class_ID_TCF_extended, ',')) %>% 
  ggplot(aes(x=families_list, y=Age)) +
    geom_point(aes(size=percent, color=percent))+
    scale_x_upset(position="top")+
  theme_classic()+
  theme(axis.title.y= element_text(angle=270))+
  scale_color_gradient(low = "#caf0f8",high = '#03045e', guide = 'legend') 

ggsave(plot,
       filename='manno_coexpression_plot_id_TCF.pdf',
       device = "pdf",
       height = 7, width =5, units = "in")  
```


```{r}
Manno_combinations_with_metadata_upset_imput %>%  
  separate_rows(class_ID_TCF_extended, sep = ', ') %>% 
  count(class_ID_TCF_extended, sort = T)
  



```

