sbatch /users/genomics/anabel/scripts/splitchr.sh danRer11.fa.gz zebrafish
sbatch /users/genomics/anabel/scripts/splitchr.sh xenTro10.fa.gz xtropicalis
sbatch /users/genomics/anabel/scripts/splitchr.sh ponAbe3.fa.gz orangutan
sbatch /users/genomics/anabel/scripts/splitchr.sh susScr11.fa.gz pig
sbatch /users/genomics/anabel/scripts/splitchr.sh ornAna2.fa.gz platypus
sbatch /users/genomics/anabel/scripts/splitchr.sh rheMac10.fa.gz macac
sbatch /users/genomics/anabel/scripts/splitchr.sh gorGor6.fa.gz gorilla
sbatch /users/genomics/anabel/scripts/splitchr.sh canFam6.fa.gz dog
sbatch /users/genomics/anabel/scripts/splitchr.sh turTru2.fa.gz dolphin
sbatch /users/genomics/anabel/scripts/splitchr.sh dm6.fa.gz drosophmelanogaster
sbatch /users/genomics/anabel/scripts/splitchr.sh loxAfr3.fa.gz elephant
sbatch /users/genomics/anabel/scripts/splitchr.sh panTro6.fa.gz chimpanzee
